#!/bin/bash
#SBATCH --job-name=f_nc_ini
#SBATCH -p compute
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --time=1:00:00
#SBATCH --output=output_ini.txt
#SBATCH -A bk1377

source /sw/etc/profile.levante
source ../env/levante.dkrz.de/shell

ulimit -s 102400

echo Submitted job: $jobid
squeue -u $USER

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

ln -s ../bin/fesom_meshpart .
cp -n ../config/namelist.config  .
cp -n ../config/namelist.forcing .
cp -n ../config/namelist.oce     .
cp -n ../config/namelist.ice     .
cp -n ../config/namelist.icepack .

date
srun -l fesom_meshpart > "fesom_meshpart.out"
date

# qstat -f $PBS_JOBID
#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job_mistral
#fi

